# Generated by Django 4.0.3 on 2022-03-25 14:29

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mentees'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mentors'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='email',
            field=models.EmailField(max_length=150, validators=[main.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='mentor',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mentor', to='main.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=150, validators=[main.models.validate_email]),
        ),
    ]
